### PR TITLE
removed selectors which made it impossible to overwrite the background color of input fields

### PR DESCRIPTION
**Pull request by bareich**
If one wants to change the background color of an input field, this would currently fail (tested in FF3.6.17) as the selectors ([type=...]) take precedence.

With this patch one is able to e.g. have a red input field with <input class="error" ... />

Let me know if it negatively influences other areas of blueprint.

### CODE REVIEW

**Comment by joshuaclayton** [comment]
This would affect _all_ the styles of checkboxes, submit buttons, etc., which we don't want. You may want to change the specificity of the selectors you're using (e.g. `body input[type=text] { background-color: red; }` would override background colors correctly) in order to add a background color.

**Comment by bareich** [comment]
So is there a way to add (for example) the 'error' class to an input field?

Like this:
&lt; input class="error" ... / &gt;
(which fails)

It feels inconsistent if a CSS framework fails to actually add a style it provides.

**Comment by joshuaclayton** [comment]
The `error` class is a class to style divs with error messages (see http://blueprintcss.org/tests/parts/forms.html near the top right) and is not intended to denote form fields with errors, which is probably why it isn't being styled as you'd expect.

**Comment by bareich** [comment]
Hmmm. My understanding was that every class was intended to work with any HTML element (in order to keep the whole framework open to different kinds of uses - and avoid superfluous div's :).

It's redundant if one has to copy/paste the definition from 
.error {background:#FBE3E4;color:#8a1f11;border-color:#FBC2C4;}

to 

input[type='text'].error {background:#FBE3E4;color:#8a1f11;border-color:#FBC2C4;}
input[type='password'].error {background:#FBE3E4;color:#8a1f11;border-color:#FBC2C4;}
... (and so forth)

just to overwrite the "strong" definition of input[type=...].

Don't you think?

**Comment by joshuaclayton** [comment]
I'm open to other ideas of how to go about this, but the original pull request that you made does not work correctly. The type selectors need to stay in there. If you can find a way to allow other uses, I'm open to hearing them or looking at another pull request. Thanks!

**Comment by bareich** [comment]
I doubt the problem can be solved from the classes side, as it's actually caused by the type-selectors.

They simply weigh to heavily.

To illustrate the issue: One person in freenet's #css channel pointed out that !important would help - but that would have to go practically everywhere (and of course destroy the whole file's logic) ...

**Comment by joshuaclayton** [comment]
Well, it seems an immovable object has met an unstoppable force! The type selectors are staying because the styles are for all text-based inputs. Luckily, Blueprint is a framework and can be overridden on a per-project basis. If you want to apply specific styles to inputs, you'll have to use a higher specificity (this article outlines the math behind it: http://www.htmldog.com/guides/cssadvanced/specificity/). Good luck.

**Comment by bareich** [comment]
Thanks for your response. The problem outlined in the link you provided is clear.

But what is the difference between selecting the INPUT types one by one (to assign styles) compared to assigning the styles directly to INPUT in general?

Sorry, if there was a misunderstanding. Of course my intention is to find a solution that keeps the rest of blueprint functional.

**Comment by joshuaclayton** [comment]
We don't want to style all inputs the same. A good example would be `input[type=hidden]` - if we were to style all inputs (without selecting by type), hidden inputs would end up looking pretty similar to inputs, which we don't want. Another example is checkboxes. These are inherently different types of input, which is why we style a subset of inputs. Does this answer your question?

**Comment by bareich** [comment]
Considering the 20+ types since HTML5, your point does make sense.

Do you think it would be reasonable if we introduce a basic style to all INPUT's while overwriting the other types with selectors?

**Comment by joshuaclayton** [comment]
It's something to look into! What would the defaults be, do you think? Note that we won't want to set margin, padding, background color, or border (just off the top of my head, since hidden inputs shouldn't have those set) - what else would be left?

**Comment by bareich** [comment]
I'd make the defauls as similar as possible to the existing input-defintions, but haven't yet looked into it more closely. (Visuals aren't my main competence :)

I think the important things (for many types) are background-color and color - would you consider it too hacky to introduce a input[type="hidden"] {display:none} in order to avoid the problem you outlined?

**Pull request closed without merging**
